# Generated by Django 3.1.1 on 2026-04-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstaff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationstaff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Parent')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
    ]
